Flask_Web/flask_web/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class Post_Form(FlaskForm):
    title = StringField('Title' , validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

Flask_Web/flask_web/main/routes.py
from flask import render_template, request, Blueprint
from flask_web.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type= int)
    posts = Post.query.paginate(page = page, per_page=2)
    return render_template('index.html', posts = posts)

@main.route("/about")
def about():
    return render_template('about.html', title = 'About')

Flask_Web/flask_web/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_web import db
from flask_web.models import Post
from flask_web.posts.forms import Post_Form



posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = Post_Form()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form = form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post= Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = Post_Form()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

Flask_Web/flask_web/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_web import db, bcrypt
from flask_web.models import User, Post
from flask_web.users.forms import (Registration_Form, Login_Form, Update_Account_Form,
                                   Request_ResetForm, Reset_Password)
from flask_web.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Registration_Form()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data} succesfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():        
    if current_user.is_authenticated: #must be True if the user has valid login credentials or False otherwise.
        return redirect(url_for('main.home'))
    form = Login_Form()
    if form.validate_on_submit():
        user = User.query.filter_by(email= form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = Update_Account_Form()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET' :
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename= current_user.image_file)
    return render_template('account.html', title='Account', image_file= image_file, form = form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type= int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Post.query.filter_by(author=user).paginate(page = page, per_page=2)
    return render_template('user_posts.html', posts = posts, user = user)


@users.route("/reset_password", methods=['GET', 'POST'])
def password_reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Request_ResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('password_reset_request.html', title='Reset Password', form = form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def password_reset(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token!', 'warning')
        return redirect(url_for('users.utils.password_reset_request'))
    form = Reset_Password()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated for {form.username.data} succesfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title= 'Reset Password', form = form)

    

Flask_Web/flask_web/templates/about.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

{% endblock %}

Flask_Web/flask_web/templates/account.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
    <div class="content-section">
        <div class="media">
        <img class="account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
        </div>
        <br>
        <br>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }} 
            <fieldset>
                <legend>Would you like to change your info?</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}

                    {% if form.username.errors %}
                    {{ form.username(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control") }}
                {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label")}}

                    {% if form.email.errors %}
                    {{ form.email(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}

                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control" )}}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="invalid-feedback">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="submit-button")}}
            </div>
        </form>
    </div>
{% endblock %}

Flask_Web/flask_web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    {% block head %}{% endblock %}
        {% if title %}
            <title>Flask Blog - {{ title }}</title>
        {% else %}
            <title> Flask Blog</title>
        {% endif %}
</head>
<body>
    <div class="topnav-bar">
        <div class="navbar-left">
            <a href="{{ url_for('main.home') }}">Home</a>
            <a class="margin" href="{{ url_for('main.about') }}">About</a>
        </div>
        <div class="navbar-right">
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('posts.new_post') }}">New Post</a>
                <a href="{{ url_for('users.account') }}">Account</a>
                <a href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
                <a href="{{ url_for('users.register') }}">Sign In</a>
                <a href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
        </div>
    </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <!-- for loop is for both cathegory and message -->
            {% for category, message in messages %}
            <div class="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block body %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Flask_Web/flask_web/templates/create_post.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="submit-button") }}
        </div>
    </form>
</div>
{% endblock %}

Flask_Web/flask_web/templates/index.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

    <input class="search-bar" type="text" placeholder="Search for a blog...">

    {% for post in posts.items %}

    <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <img class="account-img" src="{{ url_for('static', filename= post.author.image_file) }}">
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
          <div class="article-info">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          </div>
        </div>
    </article>

    {% endfor %}
    {% for page_num in posts.iter_pages() %}
      {% if page_num %}
        {% if page_num == posts.page %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num}}</a>
        {% endif %}
      {% endif %}
    {% endfor %}

{% endblock %}

Flask_Web/flask_web/templates/login.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="submit-button") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.password_reset_request') }}">Forgot Password?</a>
            </small>
        </div>
        
    </form>
</div>
<div>
    <small class="small-text">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock %}

Flask_Web/flask_web/templates/password_reset_request.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="submit-button") }}
        </div>
    </form>
</div>
{% endblock %}

Flask_Web/flask_web/templates/post.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                <img class="account-img" src="{{ url_for('static', filename= post.author.image_file) }}">
                <h2 class="article-title">{{ post.title }}</h2>
                <p class="article-content">{{ post.content }}</p>
                </div>
                <div class="article-info">
                  <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                </div>
                {% if post.author == current_user %}
                    <div>
                        <button class="submit-button"><a class="text" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a></button>
                        <button type="button" class="submit-button" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
        </article>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                  </form>
                </div>
              </div>
            </div>
          </div>
{% endblock %}

Flask_Web/flask_web/templates/register.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
    <div class="register-body">
        <div class="join-us">
            <form method="POST" action="">
                {{ form.hidden_tag() }} 
                <fieldset class="account-update">
                    <legend>JOIN US!</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label")}}

                        {% if form.username.errors %}
                        {{ form.username(class="form-control") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}

                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label")}}

                        {% if form.email.errors %}
                        {{ form.email(class="form-control") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}

                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label")}}

                        {% if form.password.errors %}
                        {{ form.password(class="form-control") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}

                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label")}}

                        {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control") }}
                    {% endif %}

                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="submit-button")}}
                </div>
            </form>
        </div>
        <div>
            <small class="small-text">
                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
        </div>
    </div>
    
{% endblock %}

Flask_Web/flask_web/templates/reset_token.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Reset Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="submit-button") }}
        </div>
    </form>
</div>
{% endblock %}

Flask_Web/flask_web/templates/user_posts.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
    <h1>Posts by {{ user.username}} ({{ posts.total }})</h1>

    {% for post in posts.items %}

    <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <img class="account-img" src="{{ url_for('static', filename= post.author.image_file) }}">
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
          <div class="article-info">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          </div>
        </div>
    </article>

    {% endfor %}
    {% for page_num in posts.iter_pages() %}
      {% if page_num %}
        {% if page_num == posts.page %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num}}</a>
        {% endif %}
      {% endif %}
    {% endfor %}

{% endblock %}